create extension if not exists "pgcrypto";

do $$ begin
  create type order_status as enum ('pending', 'confirmed', 'rejected');
exception
  when duplicate_object then null;
end $$;

create table if not exists users (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(100) not null unique,
  password varchar(255) not null,
  role varchar(20) not null check (role in ('admin', 'customer')),
  created_at timestamptz default now()
);

create table if not exists products (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  price numeric(10,2) not null,
  stock int not null default 0,
  description text,
  image varchar(255),
  created_at timestamptz default now()
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id),
  invoice_number varchar(60) not null unique,
  total numeric(10,2) not null,
  status order_status not null default 'pending',
  payment_status order_status not null default 'pending',
  payment_proof varchar(255),
  created_at timestamptz default now()
);

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint not null references products(id),
  qty int not null,
  price numeric(10,2) not null
);

insert into users (name, email, password, role)
values ('Admin Jaya', 'admin@jaya.com', 'admin123', 'admin')
on conflict (email) do nothing;

insert into products (name, price, stock, description, image)
values
  ('Brake Pad Racing', 250000, 25, 'Kampas rem performa tinggi untuk motor harian dan balap.', null),
  ('Chain Set 428', 420000, 18, 'Rantai dan gear set awet untuk touring jarak jauh.', null),
  ('LED Headlamp Pro', 180000, 45, 'Lampu LED terang dan hemat daya.', null)
on conflict do nothing;
